/** Known ROMs */
export default {
	'1942': '1942',
	'720r1': '720 Degrees',
	aburner2: 'After Burner II',
	amidar: 'Amidar',
	arkanoid: 'Arkanoid',
	asteroid: 'Asteroids',
	astrob: 'Astro Blaster',
	berzerk: 'Berzerk',
	bombjack: 'Bomber Jack',
	bombrman: 'Bomber Man',
	bosco: 'Bosconian',
	brubber: 'Burning Rubber',
	btime: 'Burger Time',
	bubbles: 'Bubbles',
	buckrog: 'Buck Rogers',
	bzone: 'Battle Zone',
	ccastles: 'Crystal Castles',
	centiped: 'Centipede',
	defender: 'Defender',
	digdug: 'Dig Dug',
	dkong: 'Donkey Kong',
	dkong3: 'Donkey Kong 3',
	dkongjr: 'Donkey Kong Jr',
	elevator: 'Elevator Action',
	exerion: 'Exerion',
	frenzy: 'Frenzy',
	frogger: 'Frogger',
	galaga: 'Galaga',
	galaxian: 'Galaxian',
	gaplus: 'Gaplus',
	gauntlet: 'Gauntlet',
	gorf: 'Gorf',
	gravitar: 'Gravitar',
	gunfight: 'Gun Fight',
	gyruss: 'Gyruss',
	invaders: 'Space Invaders',
	joust: 'Joust',
	junglek: 'Jungle King',
	junofrst: 'Juno First',
	kangaroo: 'Kangaroo',
	kchamp: 'Karate Champ',
	ladybug: 'Ladybug',
	marble: 'Marble Madness',
	mario: 'Mario',
	mhavoc: 'Major Havoc',
	missile: 'Missile Command',
	mpatrol: 'Moon Patrol',
	mrdo: 'Mr. Do!',
	mspacman: 'Ms. Pac-Man',
	narc: 'Narc',
	natodef: 'NATO Defense',
	nitedrvr: 'Night Driver',
	omegrace: 'Omega Race',
	outrun: 'Outrun',
	pacman: 'Pac-Man',
	paperboy: 'Paperboy',
	pengo: 'Pengo',
	phoenix: 'Phoenix',
	pleiads: 'Pleiads',
	polepos: 'Pole Position',
	pooyan: 'Pooyan',
	qbert: 'Q*Bert',
	qix: 'Qix',
	raiden: 'Raiden',
	rampage: 'Rampage',
	ridgerac: 'Ridge Racer',
	robotron: 'Robotron 2084',
	rtype: 'R-Type',
	scobra: 'Super Cobra',
	scramble: 'Scramble',
	seawolf: 'Sea Wolf',
	sf: 'Street Fighter',
	shollow: "Satan's Hollow",
	sinistar: 'Sinistar',
	spacewar: 'Space War',
	spacfury: 'Space Fury',
	spiders: 'Spiders',
	spyhunt: 'Spy Hunter',
	starcas: 'Star Castle',
	stargate: 'Star Gate',
	starhawk: 'Star Hawk',
	starwars: 'Star Wars',
	tailg: 'Tail Gunner',
	tapper: 'Tapper',
	tempest: 'Tempest',
	timeplt: 'Time Pilot',
	trackfld: 'Track and Field',
	tron: 'Tron',
	tutankhm: 'Tutankham',
	twincobr: 'Twin Cobra',
	vanguard: 'Vanguard',
	vf: 'Virtua Fighter',
	xevious: 'Xevious',
	zaxxon: 'Zaxxon'
} as Readonly<Record<string, string>>
